### ISSUE TITLE
This plugin does not works with Multimodule app type

### ISSUE THREAD

**Issue by alexglue** [calinrada/PhalconUserPlugin#10]
Even if i do this in my apps/frontend/Module.php:
```
    public function registerAutoloaders()
    {

        $loader = new Loader();

        $loader->registerNamespaces(array(
            'Test\Frontend\Controllers' => __DIR__ . '/controllers/',
            'Test\Frontend\Models'      => __DIR__ . '/models/',
            'Phalcon\UserPlugin'         => __DIR__ . '/plugins/UserPlugin'
```
and after this:
```

        $di->set('config', function()use($config){
            return $config;
        });
```
and
```
// /UserPlugin/Plugin/Security.php::46
        $config    = $this->config;
```
and after all debug sais:
Phalcon\Mvc\Dispatcher\Exception: Test\Frontend\Controllers\UserController handler class cannot be loaded when i trying to open http://test.local/user/login/

I do not have any idea what the problem is.
Do u test your plugin with --modules app-type at all?

**Comment by calinrada** [comment]
Working on v 2.0. It will be released in a few days
