### ISSUE TITLE
Translation service fail

### ISSUE THREAD

**Issue by alexglue** [calinrada/PhalconUserPlugin#11]
OK, UserController successfully starting now after 2 hours of debugging.
But now i've got:

```
// UserPlugin/Forms/User/LoginForm.php:22
//         $translate = $this->getDi()->get('translate');
// Phalcon\DI\Exception: Service 'translate' was not found in the dependency injection container
```

Is it base dependency?? Translation? I do not have it in my project!

**Comment by calinrada** [comment]
Working on v 2.0. It will be released in a few days. It will be removed in 2.0
