### ISSUE TITLE
Suggestions for schema fix

### ISSUE THREAD

**Issue by alexglue** [calinrada/PhalconUserPlugin#12]
Thanx for updated version!

1) Could u plz to rename user table to users? All of your entities named in plural style but `user` table.
2) It's much effective to remove user: banned, active, suspended columns and add column status;
3) Rename user_email_confirmations.modified_at column to updated_at column (like in other cases).
4) Fix foreign keys
5) Remove profile_id column from user table
6) Add postrges schema-variant

See my https://gist.github.com/alexglue/f5241525e8ef882e1b17 for details

**Comment by calinrada** [comment]
Hi @alexglue . Thank you for your contribution. I don't have too much time, but I will try to fix them asap. I don't quite understand point 1. Tables and models are named in singular, not in plural.
