### ISSUE TITLE
Example of using ACL?

### ISSUE THREAD

**Issue by mizterp** [calinrada/PhalconUserPlugin#26]
Could someone please provide an example of protecting specific actions, based on the ACL list?

It might also be a good idea to define the default GroupID in the config, instead of setting it to 2 for all new users.

**Comment by mzf** [comment]
+1 need some examples of use ACL

**Comment by mizterp** [comment]
Since I posted this I was able to figure out how to use PUP. Will see if I can share some examples during the week.
