### ISSUE TITLE
Why cann't this plugin on production?

### ISSUE THREAD

**Issue by sairoko12** [calinrada/PhalconUserPlugin#39]
https://github.com/calinrada/PhalconUserPlugin#about

I need a special config?, i can help for solve these issues/problems?, any idea?

Explain me more please

Grettings,

**Comment by calinrada** [comment]
Sorry. I have never updated README file. You can use it. I use it for tens of projects. Be sure you use branch 3.0 https://github.com/calinrada/PhalconUserPlugin/tree/v3.0.0
